name: Setup and Build
description: Setup Node.js, install dependencies, and build contracts

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
      shell: bash

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Build contracts
      run: npm run build
      shell: bash

